source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PerspectiveTransform_Example' do
  pod 'PerspectiveTransform', :path => '../'
end

target 'PerspectiveTransform_Tests' do
  pod 'PerspectiveTransform', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase', :git => 'https://github.com/neonichu/ios-snapshot-test-case'
  pod 'Nimble-Snapshots'
end
