source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

target 'Example' do
    inhibit_all_warnings!  # mute warnings from pod dependencies

    pod 'PerspectiveTransform', :path => '../'
    pod 'ImageCoordinateSpace'

    def SwiftTestingPods
        pod 'Quick'
        pod 'Nimble'
    end

    target 'Framework Unit Specs' do
        inherit! :search_paths
        SwiftTestingPods()
    end

    target 'Application Specs' do
        inherit! :search_paths
        SwiftTestingPods()
        pod 'Nimble-Snapshots'
    end

    target 'OpenCV OSX Tests' do
        platform :osx, '10.13'
        SwiftTestingPods()
    end
end
