name: Build and Test
on: [push, pull_request]
jobs:
  iOS:
      name: Test iOS 
      runs-on: macOS-latest
      steps:
        - uses: actions/checkout@v1            
        - name: iOS
          run: xcodebuild test -workspace Example/PerspectiveTransform.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone SE" | tee .ci/results/xcodebuild-ios.log
