name: Build and Test
on: [push, pull_request]
jobs:
  iOS:
      name: Test iOS
      runs-on: macOS-latest
      timeout-minutes: 15
      steps:
        - uses: actions/checkout@v2.3.2
        - name: Install Cocoapods dependencies
          run: bundle exec pod install --project-directory=Example
        - name: Unit Specs
          uses: sersoft-gmbh/xcodebuild-action@v1.1
          with:
            workspace: Example/PerspectiveTransform.xcworkspace
            scheme: Example
            destination: platform=iOS Simulator,name=iPhone 11 Pro
        - name: Report coverage
          run: bash <(curl -s 'https://codecov.io/bash') -Z -J '^PerspectiveTransform$' -X gcov -X fix
