name: Build and Test
on: [push, pull_request]
jobs:
  iOS:
      name: Test iOS 
      runs-on: macOS-latest
      steps:
        - uses: actions/checkout@v1
        - name: Install Bundle dependencies
          run: bundle install
        - name: Install Cocoapods dependencies
          run: bundle exec pod install --project-directory=Example
        - name: iOS
          run: xcodebuild test -workspace Example/PerspectiveTransform.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=iPhone SE" | xcpretty
        - name: Report coverage
          run: bash <(curl -s 'https://codecov.io/bash') -Z -J '^PerspectiveTransform$' -X gcov -X fix
